### PR TITLE
Corrected syntax error in example for postgres db

### PR DESCRIPTION
**Pull request by iptizer**
Corrected syntax error in example for postgres db

### CODE REVIEW

**Comment by sfromm** [comment]
The example comes from the ansible documentation for the postgresql module. See [https://docs.ansible.com/ansible/latest/postgresql_user_module.html](here).

```yaml
- postgresql_user:
    db: acme
    name: test
    priv: "ALL/products:ALL"
    state: absent
    fail_on_user: no
```

While I don't use that type of a privilege definition, it seems valid based on upstream's documentation.  Can you share how this doesn't work?

**Comment by sfromm** [comment]
Okay, I see that your change also does ```s/database/db/```.

**Comment by iptizer** [comment]
Actually I didn't do much testing. But I had the requirement to get a pg database as fast as possible and it didn't work like in the example. So the s/databse/db/ change seems necessary. The s#ALL/pruduct:ALL#ALL# change might not be necessary, but has a dependency on a database. Usecase for this example is someone not having time, but who wants to get a database fast. Someone who has time will figure out the dependency. That's why I think this change might make sense.

**Comment by sfromm** [comment]
Thanks for the PR!  I hope you find the role useful.

**Pull request merged**
